base: /
languages:
  -
    title: Deutsch
    enabled: true
    base: /
    typo3Language: de
    locale: de_CH.UTF-8
    iso-639-1: de
    websiteTitle: ''
    navigationTitle: Deutsch
    hreflang: de-CH
    direction: ''
    flag: ch
    languageId: 0
rootPageId: 1
websiteTitle: ExtDevTest
